// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "frankie060392/rest-api-clean-arch/internal/book/model"

	mock "github.com/stretchr/testify/mock"
)

// BookRepositoryInterface is an autogenerated mock type for the BookRepositoryInterface type
type BookRepositoryInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, book
func (_m *BookRepositoryInterface) Create(c context.Context, book *model.Book) error {
	ret := _m.Called(c, book)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Book) error); ok {
		r0 = rf(c, book)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: c, id
func (_m *BookRepositoryInterface) GetById(c context.Context, id string) (model.Book, error) {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 model.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Book, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Book); ok {
		r0 = rf(c, id)
	} else {
		r0 = ret.Get(0).(model.Book)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookRepositoryInterface creates a new instance of BookRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookRepositoryInterface {
	mock := &BookRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
