services:
  postgres:
    image: postgres
    container_name: postgres-golang-clean-arch
    ports:
      - 6555:5432
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
